version: "3.8"

services:
  # MySQL Service
  mysqlDb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"  # MySQL Database

  # Kaddem Application Service
  app-kaddem:
    depends_on:
      - mysqlDb
    image: rimmdimagh/kaddem:1.0.0
    restart: on-failure
    ports:
      - "8089:8089"  # App port
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqlDb:3306/kaddemdb?createDatabaseIfNotExist=true",
        "spring.datasource.username":"root",
        "spring.datasource.password":""
      }'

  # SonarQube Service
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"  # SonarQube

  # Nexus Service
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"  # Nexus Repository

  # Prometheus Service
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Prometheus Monitoring

volumes:
  db:
