# Étape 1 : Utiliser OpenJDK 17 basé sur Alpine comme image de base
FROM openjdk:17-jdk-alpine

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier le fichier JAR généré par ton projet dans le conteneur
COPY target/kaddem-app.jar /app/kaddem-app.jar

# Étape 4 : Exposer le port 8080 (port utilisé par défaut par Spring Boot)
EXPOSE 8080

# Étape 5 : Commande pour démarrer l'application
CMD ["java", "-jar", "/app/kaddem-app.jar"]
