version: "2"

services:

  # Service SonarQube
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9100:9000"
      - "9001:9001"
    volumes:
      - 'SonarQube_data:/opt/sonarqube/data'
      - 'SonarQube_extensions:/opt/sonarqube/extensions'
      - 'SonarQube_logs:/opt/sonarqube/logs'






    # Service Prometheus
  prometheus:
      image: prom/prometheus:latest
      ports:
        - "9091:9090"
      volumes:
        - 'prometheus-data:/prometheus'
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  grafana-data:
  prometheus-data: