version: "2"

services:

  # Service SonarQube
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9100:9000"
      - "9001:9001"
    volumes:
      - 'SonarQube_data:/opt/sonarqube/data'
      - 'SonarQube_extensions:/opt/sonarqube/extensions'
      - 'SonarQube_logs:/opt/sonarqube/logs'

  # Service Nexus
  nexus:
    image: sonatype/nexus3
    ports:
      - "8100:8081"
      - "8082:8082"
    volumes:
      - 'nexus-data:/nexus-data'



  # Service Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - 'grafana-data:/var/lib/grafana'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=07248745

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
  grafana-data: