version: "2"

services:

  # Service SonarQube
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9100:9000"
      - "9001:9001"
    volumes:
      - 'SonarQube_data:/opt/sonarqube/data'
      - 'SonarQube_extensions:/opt/sonarqube/extensions'
      - 'SonarQube_logs:/opt/sonarqube/logs'

  # Service Nexus
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - 'nexus-data:/nexus-data'

volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
